name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Create gen folder
      run: if ! [ -d "./gen" ]; then mkdir gen && cd gen && go mod init github.com/plyovchev/go-at-ocado/sort/gen; fi
      
    - name: Generate types proto file
      run: protoc -I /usr/local/include -I idl idl/sorting.proto --go_out=gen --go-grpc_out=require_unimplemented_servers=false:gen --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative
        
    - name: Generate sort proto file
      run: protoc -I /usr/local/include -I idl idl/types.proto --go_out=gen --go-grpc_out=require_unimplemented_servers=false:gen --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative
        
    - name: Test
      run: go test -v ./...
